"""Add email verification fields to User

Revision ID: 006539013ce7
Revises: 1eec682fc167
Create Date: 2025-06-24 14:34:01.587108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006539013ce7'
down_revision = '1eec682fc167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
