"""Add delivery, driver_location, payment info to Order

Revision ID: 7ac06c5ddef8
Revises: 006539013ce7
Create Date: 2025-06-24 19:38:04.706525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ac06c5ddef8'
down_revision = '006539013ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('driver_location', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_token', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('driver_location')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
